name: "Publish Release"
on:
  release:
    types: ["published"]

jobs:
  publish_release:
    runs-on: "self-hosted"
    if: "!contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[ci-skip]')"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Setup .NET"
        uses: "actions/setup-dotnet@v1"
        with:
          dotnet-version: "6.0.x"

      - name: Test
        run: dotnet test --verbosity normal

      - name: "Build Nuget Packages"
        run: "mkdir build && dotnet pack -p:SymbolPackageFormat=snupkg --include-symbols -c Release -o build"

      - name: "Publish Nuget Packages"
        run: "dotnet nuget push \"build/*\" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json"

      - name: "Upload Nuget Packages To Github Release"
        uses: "ncipollo/release-action@v1"
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "build/*"
          token: ${{ secrets.REPO_GITHUB_TOKEN }}
          omitBodyDuringUpdate: true # We don't want to update the body of the release.
          omitNameDuringUpdate: true # We don't want to update the name of the release.